name: JWU Test
favicon: null
layout_spectrum: 0.59014
typography_spectrum: 0.66458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.25
  lightness: 0.8466955174226314
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
